name: Deploy the container app to Azure
on: [push, workflow_dispatch]

env:
    IMAGE: flask-demo
    app_name: sbarakat-webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout Github Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{vars.DOCKER_REGISTRY_SERVER_URL}}
        username: ${{ vars.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}
    
    - name: Set image version
      id: image-version
      run: echo "::set-output name=version::$(date +'%Y.%m.%d.%H.%M')"
    
    - name: 'Build and push image'
      run: |
        docker build . -t ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/${{env.IMAGE}}:${{ steps.image-version.outputs.version }}
        docker build . -t ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/${{env.IMAGE}}:latest
        docker push ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/${{env.IMAGE}}:${{ steps.image-version.outputs.version }}
        docker push ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/${{env.IMAGE}}:latest

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app_name }}
        images: '${{vars.DOCKER_REGISTRY_SERVER_URL}}/${{env.IMAGE}}:latest'

        